services:
  PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler:
    class: PrestaShop\Module\PsEventbus\Handler\ErrorHandler\ErrorHandler
    arguments:
      - '@ps_eventbus'
      - '@PrestaShop\Module\PsEventbus\Config\Env'
      - '@ps_eventbus.context'
