name: Release and publish
on:
  push:
    branches:
      - fix/test-ci

jobs:
  publish_to_marketplace:
    name: Publish the module to the addons marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Prepare publishing tool
        run: |
          composer global require prestashop/publish-on-marketplace

      - name: Release zip
        run: |
          export CHANGELOG="${CHANGELOG:=No changelog provided}"
          echo ~/.composer/vendor/bin/publish-on-marketplace \
            --archive=$PWD/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip \
            --metadata-json=$PWD/.github/mktp-metadata.json \
            --changelog="$CHANGELOG" \
            --api-key="${{ secrets.MARKETPLACE_API_KEY }}" \
            --debug
        env:
          CHANGELOG: ${{ github.event.release.body }}
