name: Add a release draft
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Add or update release draft
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find tag
        id: tagger
        uses: jimschubert/query-tag-action@v1

      - name: Get release info
        id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "${{ steps.tagger.outputs.tag }}"
          name: "${{ steps.tagger.outputs.tag }}"

      - name: Clean existing assets
        shell: bash
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          assets=`bin/hub api -t repos/${{ github.repository }}/releases/${{ steps.release_info.outputs.id }}/assets | awk '/\].url/ { print $2 }'`
          for asset in $assets
          do
            bin/hub api -X DELETE $asset
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        run: make version
        env:
          VERSION: ${{ steps.tagger.outputs.tag }}

      - name: Build
        run: |
          make
          make zip
        env:
          VERSION: ${{ steps.tagger.outputs.tag }}

      - name: Push the new assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          asset_path: ./dist/${{ github.event.repository.name }}-${{ steps.tagger.outputs.tag }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ steps.tagger.outputs.tag }.zip
          asset_content_type: application/zip
