name: Release drafter
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    name: Add or update release draft
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GA_ACCESS_TOKEN }}
        with:
          config-name: release-drafter.yml
